import type {
  TransactionListItem,
  SpendingCategory,
  TransactionDetail,
  PaymentMethod,
  AgentKey,
  Agent,
} from "./types"

export const mockTransactions: TransactionListItem[] = [
  {
    id: "txn_001",
    status: "APPROVED",
    product_name: "Nike Air Max 90",
    price: 89.99,
    currency: "USD",
    merchant_name: "Amazon.com",
    merchant_domain: "amazon.com",
    detected_category_name: "Footwear",
    decision: "APPROVE",
    decision_reason: "Within Footwear budget and trusted merchant. Auto-approved.",
    virtual_card_last_four: "8847",
    virtual_card_status: "USED",
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    decided_at: new Date(Date.now() - 1000 * 60 * 5 + 2000).toISOString(),
  },
  {
    id: "txn_002",
    status: "DENIED",
    product_name: "Sony WH-1000XM5 Headphones",
    price: 349.99,
    currency: "USD",
    merchant_name: "Best Buy",
    merchant_domain: "bestbuy.com",
    detected_category_name: "Electronics",
    decision: "DENY",
    decision_reason:
      "Price $349.99 would exceed your monthly Electronics limit. You've spent $1,800.00 this month against a $2,000.00 monthly limit.",
    virtual_card_last_four: null,
    virtual_card_status: null,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    decided_at: new Date(Date.now() - 1000 * 60 * 30 + 3000).toISOString(),
  },
  {
    id: "txn_003",
    status: "PENDING_APPROVAL",
    product_name: "Marriott NYC - 2 nights",
    price: 578.0,
    currency: "USD",
    merchant_name: "Marriott.com",
    merchant_domain: "marriott.com",
    detected_category_name: "Travel",
    decision: "REQUIRE_APPROVAL",
    decision_reason: "Travel purchases require your approval.",
    virtual_card_last_four: null,
    virtual_card_status: null,
    created_at: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    decided_at: null,
  },
  {
    id: "txn_004",
    status: "PENDING_EVALUATION",
    product_name: "ASICS Gel-Contend 8",
    price: 59.99,
    currency: "USD",
    merchant_name: "Amazon.com",
    merchant_domain: "amazon.com",
    detected_category_name: null,
    decision: null,
    decision_reason: null,
    virtual_card_last_four: null,
    virtual_card_status: null,
    created_at: new Date(Date.now() - 1000 * 10).toISOString(),
    decided_at: null,
  },
  {
    id: "txn_005",
    status: "APPROVED",
    product_name: "Anker USB-C Charger",
    price: 24.99,
    currency: "USD",
    merchant_name: "Amazon.com",
    merchant_domain: "amazon.com",
    detected_category_name: "Electronics",
    decision: "APPROVE",
    decision_reason: "Under $100 auto-approve threshold. Trusted merchant.",
    virtual_card_last_four: "3291",
    virtual_card_status: "USED",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    decided_at: new Date(Date.now() - 1000 * 60 * 60 * 2 + 1500).toISOString(),
  },
  {
    id: "txn_006",
    status: "COMPLETED",
    product_name: "Adidas Ultraboost 22",
    price: 129.99,
    currency: "USD",
    merchant_name: "Nike.com",
    merchant_domain: "nike.com",
    detected_category_name: "Footwear",
    decision: "APPROVE",
    decision_reason: "Approved by user after manual review.",
    virtual_card_last_four: "7412",
    virtual_card_status: "USED",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    decided_at: new Date(Date.now() - 1000 * 60 * 60 * 5 + 45000).toISOString(),
  },
]

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: "pm_visa_001",
    label: "Work Visa Card",
    type: "CREDIT_CARD",
    provider: "visa",
    is_default: true,
    is_active: true,
  },
  {
    id: "pm_amex_001",
    label: "Travel Amex Card",
    type: "CREDIT_CARD",
    provider: "amex",
    is_default: false,
    is_active: true,
  },
]

export const mockAgents: Agent[] = [
  {
    id: "agent_demo_001",
    name: "Personal Shopper",
    description: "My everyday shopping agent",
    is_active: true,
    created_at: "2026-02-20T10:00:00Z",
    updated_at: "2026-02-20T10:00:00Z",
  },
]

export const mockAgentKeys: AgentKey[] = [
  {
    id: "ak_demo_001",
    key_prefix: "argus_ak_7f3b",
    label: "Demo Shopping Agent",
    is_active: true,
    last_used_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
]

export const mockCategories: SpendingCategory[] = [
  {
    id: "cat_footwear_001",
    name: "Footwear",
    description: "This category covers all footwear purchases including sneakers, running shoes, boots, sandals, and slippers. Only buy from well-known retailers like Nike, Zappos, Amazon, and Target. Avoid reseller or auction sites. Purchases under $80 from whitelisted merchants can be auto-approved.",
    keywords: ["shoes", "sneakers", "boots", "running shoes", "sandals", "slippers"],
    is_default: false,
    display_order: 1,
    payment_method: {
      id: "pm_visa_001",
      label: "Work Visa Card",
      type: "CREDIT_CARD",
      provider: "visa",
      is_default: true,
      is_active: true,
    },
    rules: [
      { id: "r1", rule_type: "MAX_PER_TRANSACTION", value: "200.00", is_active: true },
      { id: "r2", rule_type: "AUTO_APPROVE_UNDER", value: "80.00", is_active: true },
      { id: "r3", rule_type: "DAILY_LIMIT", value: "300.00", is_active: true },
      {
        id: "r4",
        rule_type: "MERCHANT_WHITELIST",
        value: '["amazon.com","nike.com","zappos.com","target.com","bestbuy.com"]',
        is_active: true,
      },
    ],
    spending_today: 89.99,
    spending_this_week: 219.98,
    spending_this_month: 350.0,
  },
  {
    id: "cat_electronics_001",
    name: "Electronics",
    description: "Covers computers, phones, tablets, monitors, peripherals, and tech accessories. Prefer purchases from Amazon, Best Buy, and manufacturer stores (apple.com, dell.com). Items under $100 like cables and small accessories can be auto-approved. Anything over $500 must be flagged for manual review. Do not purchase refurbished or open-box items unless the user specifically asks for them.",
    keywords: ["laptop", "phone", "headphones", "charger", "tablet", "computer", "monitor", "keyboard"],
    is_default: false,
    display_order: 2,
    payment_method: {
      id: "pm_amex_001",
      label: "Travel Amex Card",
      type: "CREDIT_CARD",
      provider: "amex",
      is_default: false,
      is_active: true,
    },
    rules: [
      { id: "r5", rule_type: "MAX_PER_TRANSACTION", value: "500.00", is_active: true },
      { id: "r6", rule_type: "AUTO_APPROVE_UNDER", value: "100.00", is_active: true },
      { id: "r7", rule_type: "MONTHLY_LIMIT", value: "2000.00", is_active: true },
    ],
    spending_today: 24.99,
    spending_this_week: 24.99,
    spending_this_month: 1824.99,
  },
  {
    id: "cat_travel_001",
    name: "Travel",
    description: "Covers flights, hotels, car rentals, Airbnb stays, and travel accessories like luggage. All travel purchases require manual approval regardless of amount. Prefer booking through Marriott, Airbnb, Booking.com, Expedia, or airline direct sites. Budget hotels under $200/night are acceptable. Flag any first-class or business-class flights for review.",
    keywords: ["flight", "hotel", "airbnb", "booking", "rental car", "luggage", "travel"],
    is_default: false,
    display_order: 3,
    payment_method: {
      id: "pm_amex_001",
      label: "Travel Amex Card",
      type: "CREDIT_CARD",
      provider: "amex",
      is_default: false,
      is_active: true,
    },
    rules: [
      { id: "r8", rule_type: "MAX_PER_TRANSACTION", value: "2000.00", is_active: true },
      { id: "r9", rule_type: "ALWAYS_REQUIRE_APPROVAL", value: "true", is_active: true },
      { id: "r10", rule_type: "MONTHLY_LIMIT", value: "5000.00", is_active: true },
    ],
    spending_today: 0,
    spending_this_week: 0,
    spending_this_month: 578.0,
  },
  {
    id: "cat_general_001",
    name: "General",
    description: "Catch-all category for purchases that don't match any other category. Auto-approve small everyday items under $50 like household goods or office supplies. Anything above $50 should be flagged for review. Be cautious with unfamiliar merchants — if the merchant seems suspicious or unrelated to the user's request, deny the purchase.",
    keywords: [],
    is_default: true,
    display_order: 99,
    payment_method: null,
    rules: [
      { id: "r11", rule_type: "MAX_PER_TRANSACTION", value: "500.00", is_active: true },
      { id: "r12", rule_type: "AUTO_APPROVE_UNDER", value: "50.00", is_active: true },
      { id: "r13", rule_type: "DAILY_LIMIT", value: "1000.00", is_active: true },
    ],
    spending_today: 0,
    spending_this_week: 0,
    spending_this_month: 0,
  },
]

export const mockTransactionDetail: TransactionDetail = {
  id: "txn_001",
  status: "APPROVED",
  product_name: "Nike Air Max 90",
  product_url: "https://amazon.com/dp/B09EXAMPLE",
  price: 89.99,
  currency: "USD",
  merchant_name: "Amazon.com",
  merchant_url: "https://amazon.com/checkout",
  merchant_domain: "amazon.com",
  conversation_context:
    "User asked: find me running shoes under $100. I searched Amazon, found multiple options. Nike Air Max 90 at $89.99 had the best reviews and is within budget.",
  detected_category_id: "cat_footwear_001",
  detected_category_name: "Footwear",
  category_confidence: 0.94,
  rules_checked: [
    {
      rule_id: "r1",
      rule_type: "MAX_PER_TRANSACTION",
      threshold: 200.0,
      actual_value: 89.99,
      passed: true,
      detail: "89.99 <= 200.00",
    },
    {
      rule_id: "r3",
      rule_type: "DAILY_LIMIT",
      threshold: 300.0,
      actual_value: 134.99,
      breakdown: { previously_spent: 45.0, this_transaction: 89.99 },
      passed: true,
      detail: "45.00 + 89.99 = 134.99 <= 300.00",
    },
    {
      rule_id: "r4",
      rule_type: "MERCHANT_WHITELIST",
      merchant_domain: "amazon.com",
      whitelist: ["amazon.com", "nike.com", "zappos.com", "target.com"],
      passed: true,
      detail: "amazon.com is in whitelist",
    },
    {
      rule_id: "r2",
      rule_type: "AUTO_APPROVE_UNDER",
      threshold: 80.0,
      actual_value: 89.99,
      passed: false,
      detail: "89.99 >= 80.00 — cannot auto-approve, needs human review",
    },
  ],
  ai_evaluation: {
    category_name: "Footwear",
    category_confidence: 0.94,
    intent_match: 0.92,
    intent_summary:
      "User asked for running shoes under $100. Agent found Nike Air Max 90 for $89.99. Good match on product type and price range.",
    risk_flags: [],
    reasoning:
      "Product closely matches user intent. Price within stated budget constraint. Amazon.com is a well-established merchant.",
  },
  decision: "APPROVE",
  decision_reason: "Within Footwear budget and trusted merchant. Auto-approved.",
  decided_at: new Date(Date.now() - 1000 * 60 * 5 + 2000).toISOString(),
  approval_requested_at: null,
  approval_responded_at: null,
  approved_by: "AUTO",
  virtual_card: {
    card_number: "4532789012348847",
    expiry_month: "03",
    expiry_year: "2026",
    cvv: "731",
    last_four: "8847",
    spend_limit: 103.49,
    merchant_lock: "amazon.com",
    expires_at: new Date(Date.now() + 1000 * 60 * 25).toISOString(),
  },
  created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  updated_at: new Date(Date.now() - 1000 * 60 * 5 + 2000).toISOString(),
}
